### ISSUE TITLE
Figure out how to deploy the web app on AWS

### ISSUE THREAD

**Issue by zromano** [zromano24/Capture-The-Flag#1]
It will be a Java SpringBoot application. 

Links that may be helpful:
( I didn't actually read them, but the titles were spot on for what we want).

- https://www.javacodegeeks.com/2019/10/deploy-spring-boot-application-aws-ec2-instance.html
- https://www.nexsoftsys.com/articles/how-to-deploy-spring-boot-application-in-aws-ec2-server-quickly.html

If we don't use an EC2 instance, Beanstalk will probably be much easier for ### deployment:

https://aws.amazon.com/blogs/devops/deploying-a-spring-boot-application-on-aws-using-aws-elastic-beanstalk/

**Comment by JenTzori** [comment]
Finished EC2 solution with https://www.javacodegeeks.com/2019/10/deploy-spring-boot-application-aws-ec2-instance.html, see slack for link.

**Comment by JenTzori** [comment]
Finished Elastic Beanstalk solution with https://aws.amazon.com/blogs/devops/deploying-a-spring-boot-application-on-aws-using-aws-elastic-beanstalk/ (though it was actually much simpler). see slack for link
