### ISSUE TITLE
S3 Bucket URL serves image

### ISSUE THREAD

**Issue by JenTzori** [zromano24/Capture-The-Flag#7]
When a user logs into their user page, there is an image whose source is our unsecured S3 bucket. The attacker can inspect element to determine the source of that image, see that it is an S3 bucket, and visit the S3 bucket.

**Comment by JenTzori** [comment]
See https://us-election-ctf.s3.amazonaws.com/flag-400.png

**Comment by mvande17** [comment]
Added the flag jpg to the admin.html page
